const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let profile=JSON.parse(localStorage.getItem('core1QuestProfile')||'{"xp":0,"best":0}');
let history=JSON.parse(localStorage.getItem('core1QuestHistory')||'[]');
let run=[],idx=0,score=0,streak=0,best=0,earned=0,selected=new Set(),locked=false,lastTopic=null,matchState={},activeMatch=null;
const topics=[...new Set(QUESTION_BANK.map(q=>q.topic))].sort();
function save(){localStorage.setItem('core1QuestProfile',JSON.stringify(profile));renderStats()}
function renderStats(){let level=Math.floor(profile.xp/100)+1,part=profile.xp%100;$('#xp').textContent=profile.xp;$('#level').textContent=level;$('#levelBar').style.width=part+'%';$('#levelText').textContent=`${part} / 100 XP`;$('#streak').textContent=streak}
function saveHistory(){localStorage.setItem('core1QuestHistory',JSON.stringify(history));renderHistory()}
function renderHistory(){let box=$('#historyList');if(!box)return;if(!history.length){box.innerHTML='<div class="history-empty">No completed exams yet. Finish a quest and your score will appear here.</div>';return}box.innerHTML=history.map((x,i)=>`<div class="history-item"><div><b>${x.topic}</b><small>${new Date(x.date).toLocaleString()}</small></div><div class="history-score"><strong>${x.pct}%</strong><span>${x.score} / ${x.total} correct</span></div></div>`).join('')}
function screen(id){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');scrollTo(0,0)}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function start(topic=null){lastTopic=topic;let pool=topic?QUESTION_BANK.filter(q=>q.topic===topic):QUESTION_BANK;run=shuffle(pool).slice(0,Math.min(+$('#amount').value,pool.length));idx=score=streak=best=earned=0;screen('quiz');showQuestion()}
function showQuestion(){
  locked=false;selected.clear();matchState={};activeMatch=null;let q=run[idx];
  $('#counter').textContent=`${idx+1} / ${run.length}`;$('#progressBar').style.width=`${idx/run.length*100}%`;$('#topicLabel').textContent=q.topic;
  $('#question').textContent=q.question;$('#feedback').classList.add('hidden');$('#next').classList.add('hidden');$('#submit').classList.remove('hidden');$('#submit').disabled=true;$('#answers').innerHTML='';
  if(q.type==='matching'){ $('#multiLabel').textContent='DRAG & DROP • MATCH ALL'; renderMatching(q); }
  else { $('#multiLabel').textContent=q.answers.length>1?'SELECT ALL THAT APPLY':'SELECT ONE ANSWER';Object.entries(q.options).forEach(([l,t])=>{let b=document.createElement('button');b.className='answer';b.dataset.letter=l;b.innerHTML=`<span class="letter">${l}</span><span class="answer-text">${t}</span>`;b.onclick=()=>pick(l,b);$('#answers').appendChild(b)}); }
  renderStats();
}
function renderMatching(q){
  const box=$('#answers');box.className='answers matching-board';
  const source=document.createElement('div');source.className='match-column';source.innerHTML='<h3>Accessories</h3>';
  Object.keys(q.pairs).forEach(key=>{let item=document.createElement('button');item.type='button';item.className='match-item';item.draggable=true;item.dataset.key=key;item.textContent=key;item.addEventListener('dragstart',e=>{activeMatch=key;e.dataTransfer.setData('text/plain',key);item.classList.add('dragging')});item.addEventListener('dragend',()=>item.classList.remove('dragging'));item.onclick=()=>selectMatchSource(key,item);source.appendChild(item)});
  const targets=document.createElement('div');targets.className='match-column';targets.innerHTML='<h3>Drop on the matching choice</h3>';
  shuffle(Object.values(q.pairs)).forEach(value=>{let target=document.createElement('button');target.type='button';target.className='match-target';target.dataset.value=value;target.innerHTML=`<span class="target-text">${value}</span><span class="match-slot">Drop accessory here</span>`;target.addEventListener('dragover',e=>{e.preventDefault();target.classList.add('drag-over')});target.addEventListener('dragleave',()=>target.classList.remove('drag-over'));target.addEventListener('drop',e=>{e.preventDefault();target.classList.remove('drag-over');assignMatch(e.dataTransfer.getData('text/plain')||activeMatch,value)});target.onclick=()=>{if(activeMatch)assignMatch(activeMatch,value)};targets.appendChild(target)});
  box.append(source,targets);
}
function selectMatchSource(key,item){if(locked)return;activeMatch=key;$$('.match-item').forEach(x=>x.classList.toggle('selected',x.dataset.key===key));}
function assignMatch(key,value){if(locked||!key)return;Object.keys(matchState).forEach(k=>{if(matchState[k]===value)delete matchState[k]});matchState[key]=value;activeMatch=null;$$('.match-item').forEach(x=>x.classList.remove('selected'));updateMatchUI();$('#submit').disabled=Object.keys(matchState).length!==Object.keys(run[idx].pairs).length;}
function updateMatchUI(){let q=run[idx];$$('.match-target').forEach(t=>{let key=Object.keys(matchState).find(k=>matchState[k]===t.dataset.value);let slot=t.querySelector('.match-slot');slot.textContent=key||'Drop accessory here';t.classList.toggle('filled',!!key)});$$('.match-item').forEach(i=>i.classList.toggle('placed',Object.prototype.hasOwnProperty.call(matchState,i.dataset.key)));}
function pick(l,b){if(locked)return;let q=run[idx];if(q.answers.length===1){selected=new Set([l]);$$('.answer').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')}else{selected.has(l)?selected.delete(l):selected.add(l);b.classList.toggle('selected')}$('#submit').disabled=selected.size===0}
function check(){
  if(locked)return;let q=run[idx];
  if(q.type==='matching')return checkMatching(q);
  if(!selected.size)return;locked=true;let ok=q.answers.length===selected.size&&q.answers.every(x=>selected.has(x));award(ok);$$('.answer').forEach(b=>{let l=b.dataset.letter,isChosen=selected.has(l),isCorrect=q.answers.includes(l);b.classList.remove('selected');if(isChosen&&isCorrect){b.classList.add('correct','chosen-correct');b.insertAdjacentHTML('beforeend','<span class="choice-status">✓ Your answer — Correct</span>')}else if(isChosen&&!isCorrect){b.classList.add('wrong','chosen-wrong');b.insertAdjacentHTML('beforeend','<span class="choice-status">✕ Your answer — Incorrect</span>')}else if(isCorrect){b.classList.add('correct','actual-correct');b.insertAdjacentHTML('beforeend','<span class="choice-status">✓ Correct answer</span>')}b.disabled=true});showFeedback(q,ok);
}
function award(ok){if(ok){score++;streak++;best=Math.max(best,streak);earned+=10;profile.xp+=10}else{streak=0;earned+=2;profile.xp+=2}profile.best=Math.max(profile.best||0,best);save();}
function checkMatching(q){if(Object.keys(matchState).length!==Object.keys(q.pairs).length)return;locked=true;let ok=Object.entries(q.pairs).every(([k,v])=>matchState[k]===v);award(ok);$$('.match-target').forEach(t=>{let key=Object.keys(matchState).find(k=>matchState[k]===t.dataset.value),correct=key&&q.pairs[key]===t.dataset.value;t.classList.add(correct?'correct':'wrong');t.disabled=true});$$('.match-item').forEach(i=>i.disabled=true);showFeedback(q,ok);}
function showFeedback(q,ok){let f=$('#feedback');f.classList.remove('hidden');let detail=q.type==='matching'?Object.entries(q.explanations).map(([k,e])=>`<div class="explain"><b>${k}</b><br>${e}</div>`).join(''):Object.entries(q.explanations).map(([l,e])=>`<div class="explain"><b>${l}. ${q.options[l]}</b><br>${e}</div>`).join('');f.innerHTML=`<h3 class="${ok?'good':'bad'}">${ok?'✓ Correct! +10 XP':'✦ Training point +2 XP'}</h3>${detail}${q.tip?`<div class="tip"><b>💡 Remember Tip:</b> ${q.tip}</div>`:''}`;$('#submit').classList.add('hidden');$('#next').classList.remove('hidden');renderStats();}
function finish(){screen('results');let pct=Math.round(score/run.length*100);let topic=lastTopic||'Random Quest';history.unshift({topic,score,total:run.length,pct,date:new Date().toISOString()});history=history.slice(0,100);saveHistory();$('#scorePct').textContent=pct+'%';$('#earnedXp').textContent='+'+earned;$('#bestStreak').textContent=best;$('#resultLine').textContent=`You got ${score} of ${run.length} questions correct.`;$('#resultEmoji').textContent=pct>=90?'🏆':pct>=75?'⭐':pct>=60?'⚡':'🧠';$('#resultMessage').textContent=pct>=90?'Excellent work — you owned this quest!':pct>=75?'Strong run. Review the missed explanations and go again.':pct>=60?'Good progress. Every missed question showed you what to train next.':'This was training, not failure. Review the tips and your next run will be stronger.'}
$('#resetProgress').onclick=()=>{if(!confirm('Reset all XP and progress for this game? This cannot be undone.'))return;profile={xp:0,best:0};localStorage.removeItem('core1QuestProfile');streak=0;best=0;earned=0;renderStats();alert('Progress reset! You are back to Level 1 with 0 XP.');};$('#resetHistory').onclick=()=>{if(!history.length){alert('There is no exam history to reset yet.');return}if(!confirm('Reset all exam score history for this game? Your XP will stay the same.'))return;history=[];localStorage.removeItem('core1QuestHistory');renderHistory();alert('Exam history reset. Your XP and level were not changed.');};$('#next').onclick=()=>{idx++;idx>=run.length?finish():showQuestion()};$('#submit').onclick=check;$('#quickStart').onclick=()=>start();$('#quit').onclick=()=>screen('home');$('#homeBtn').onclick=()=>screen('home');$('#again').onclick=()=>start(lastTopic);
const counts=Object.fromEntries(topics.map(t=>[t,QUESTION_BANK.filter(q=>q.topic===t).length]));topics.forEach(t=>{let b=document.createElement('button');b.className='topic';b.innerHTML=`<b>⚡ ${t}</b><small>${counts[t]} questions</small>`;b.onclick=()=>start(t);$('#topics').appendChild(b)});renderStats();renderHistory();
